### ISSUE TITLE
新居で引っ越し祝いのパーティーを開く

### ISSUE THREAD

**Issue by wafrelka** [osyoyu/hikkoshi#10]

**Comment by osyoyu** [comment]
費用は @wafrelka さん持ちでお願いします

**Comment by wafrelka** [comment]
エーッ

**Comment by wafrelka** [comment]
issue なにも close されてないし引っ越しに失敗したように見えるのでお祝いするのはやめます……。

**Comment by osyoyu** [comment]
@wafrelka 引越し完了しました

**Comment by osyoyu** [comment]
@wafrelka まだパーティーしていないので close しないでください

**Comment by wafrelka** [comment]
おしょーゆハウスでパーティーするまえに次の引っ越しが発生しそうなのでパーティー会場がなくなった

**Comment by wafrelka** [comment]
今日やったのでやっと close できます
